// captures food truck properties
export interface FoodTruck {
    locationId: number,
    applicant: string,
    facilityType: string,
    cnn: string,
    locationDescription: string,
    address: string,
    blocklot: string,
    block: string,
    lot: string,
    permit: string,
    status: string,
    foodItems: string,
    X: string,
    Y: string,
    latitude: string,
    longitude: string,
    schedule: string,
    dayshours: string,
    NOISent: string,
    approved: string,
    received: string,
    PriorPermit: string,
    expirationDate: string,
    location: string,
    firePreventionDistricts: string,
    policeDistricts: string,
    supervisorDistricts: string,
    zipCodes: string,
    neighborhoodsOld: string,
    [key: string]: string | number
}